# Configuration for https://crowdin.com/project/lambda-node

project_id: 398054
base_path: .
base_url: https://api.crowdin.com
preserve_hierarchy: false

commit_message: |-
 New translations: %language%

 Source file: `%original_file_name%`

 Translators, thank you for making Lambda usable by everyone in the world!

 Commit created automatically by Crowdin.

 Test plan: `lambda-qt`

append_commit_message: false

files: [
 {
  source: /src/qt/locale/lambda_en.ts,
  translation: /src/qt/locale/lambda_%locale_with_underscore%.ts,
 }
]
