FROM ubuntu:16.04

RUN apt-get update && apt-get install -y doxygen graphviz

COPY doc /lambda-node/doc
COPY src /lambda-node/src

WORKDIR /lambda-node

RUN doxygen doc/Doxyfile

FROM nginx:alpine

COPY --from=0 /lambda-node/doc/doxygen/html /usr/share/nginx/html
