#pragma once
/**
 * List of fixed seed nodes for the Lambda main and test networks
 * @generated by contrib/seeds/generate-seeds.py
 *
 * Each string must be numeric IPv4 dot-notation or numeric
 * IPv6 hex notation, followed by a colon and a port.
 */
static const SeedSpec6 pnSeed6_main[] = {
    { "154.251.81.112:9333" },
    { "154.240.0.0:9333" }
};

static const SeedSpec6 pnSeed6_testnet3[] = {
      { "154.251.81.112:19333" },
    { "154.240.0.0:19333" }
};

static const SeedSpec6 pnSeed6_testnet4[] = {
      { "154.251.81.112:29333" },
    { "154.240.0.0:29333" }
};

static const SeedSpec6 pnSeed6_scalenet[] = {
      { "154.251.81.112:39333" },
    { "154.240.0.0:39333" }
};
